{% set name = "safetensors" %}

package:
  name: "{{ name|lower }}"
  version: "{{ SAFETENSORS_VERSION }}"

source:
  path: ../../

requirements:
  host:
    - pip
    - python x.x
    - setuptools
    - setuptools-rust
    - maturin

  run:
    - python x.x

test:
  imports:
    - safetensors

about:
  home: https://huggingface.co/docs/safetensors
  license: Apache License 2.0
  license_file: LICENSE
  summary: "Safe and portable way of storing tensors"
