repos:
  - repo: https://github.com/Narsil/pre-commit-rust
    rev: 0c016cee78144d06d906fccc7715d607a946ca5c
    hooks:
      - id: fmt
        name: "Rust (fmt)"
        args: ["--manifest-path", "safetensors/Cargo.toml", "--"]
      - id: clippy
        name: "Rust (clippy)"
        args:
          [
            "--manifest-path",
            "safetensors/Cargo.toml",
            "--all-targets",
            "--",
            "-Dwarnings",
          ]
  - repo: https://github.com/Narsil/pre-commit-rust
    rev: 0c016cee78144d06d906fccc7715d607a946ca5c
    hooks:
      - id: fmt
        name: "Python (fmt)"
        args: ["--manifest-path", "bindings/python/Cargo.toml", "--"]
      - id: clippy
        name: "Python (clippy)"
        args:
          [
            "--manifest-path",
            "bindings/python/Cargo.toml",
            "--all-targets",
            "--",
            "-Dwarnings",
          ]
  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black
        name: "Python (black)"
        args: ["--line-length", "119", "--target-version", "py35"]
        types: ["python"]
  - repo: https://github.com/pycqa/flake8
    rev: 7.2.0
    hooks:
      - id: flake8
        args: ["--config", "bindings/python/setup.cfg"]
  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.7.0 # Use the revision sha / tag you want to point at
    hooks:
      - id: isort
