blank_issues_enabled: true
version: 2.1
contact_links:
  - name: Model checkpoints on the Hugging Face Hub
    url: https://huggingface.co/models
    about: Open a Pull request / Discussion related to a specific model checkpoint directly on the Hugging Face Hub
  - name: Website Related
    url: https://github.com/huggingface/hub-docs/issues
    about: Feature requests and bug reports related to the website
  - name: Forum
    url: https://discuss.huggingface.co/
    about: General usage questions and community discussions
