name: Build documentation

on:
  push:
    branches:
      - main
      - doc-builder*
      - v*-release
      - use_templates

jobs:
  build:
    uses: huggingface/doc-builder/.github/workflows/build_main_documentation.yml@main
    with:
      commit_sha: ${{ github.sha }}
      package: safetensors
      notebook_folder: safetensors_doc
      package_path: safetensors/bindings/python/
      install_rust: true
    secrets:
      token: ${{ secrets.HUGGINGFACE_PUSH }}
