name: Code coverage
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./safetensors

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd  # v6.0.2

      - name: Install Rust Stable
        uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8  # stable
        with:
          components: llvm-tools-preview
          override: true

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32  # v2

      - name: Install cargo-llvm-cov for Ubuntu
        run: cargo install cargo-llvm-cov

      - name: Coverage report
        run: cargo llvm-cov --release --lcov --output-path lcov.info

      - name: Upload to codecov.io
        uses: codecov/codecov-action@75cd11691c0faa626561e295848008c8a7dddffe  # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          working-directory: ./safetensors
          fail_ci_if_error: true
