name: Delete dev documentation

on:
  pull_request:
    types: [ closed ]
    paths:
      - "docs/**"
      - "bindings/python/py_src/**"


jobs:
  delete:
    uses: huggingface/doc-builder/.github/workflows/delete_doc_comment.yml@main
    with:
      pr_number: ${{ github.event.number }}
      package: safetensors